admin-console-token: S3Cr3tP4$$W0rD
append-user-to-subdomain: false
authentication-keys-directory: deploy/pubkeys/
authentication-password: S3Cr3tP4$$W0rD
banned-countries: ""
banned-ips: ""
banned-subdomains: localhost
bind-random-ports: true
bind-random-subdomains: true
certificate-directory: deploy/ssl/
cleanup-unbound: true
cleanup-unbound-timeout: 5s
config: config.yml
connection-idle-timeout: 5s
debug: false
domain: ssi.sh
enable-admin-console: false
enable-authentication: false
enable-geodb: false
enable-https: false
enable-log-to-client: false
enable-proxy-protocol: false
enable-redirect-root: true
enable-service-console: false
enable-tcp-aliases: false
http-address: localhost:80
http-port-override: 0
https-address: localhost:443
https-port-override: 0
max-subdomain-length: 3
ping-client: true
ping-client-interval: 5s
port-bind-range: 0,1024-65535
private-key-location: deploy/keys/ssh_key
private-key-passphrase: S3Cr3tP4$$phrAsE
proxy-protocol-version: "1"
redirect-root-location: https://github.com/antoniomika/sish
service-console-token: ""
ssh-address: localhost:2222
user-subdomain-separator: ""
verify-origin: true
verify-ssl: true
whitelisted-countries: ""
whitelisted-ips: ""
